site_name: Runnel
site_description: >-
  The Solution to Micro Frontend Communication
repo_name: runneljs/runnel
repo_url: https://github.com/runneljs/runnel
theme:
  name: material
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  features:
    - search.suggest
    - search.highlight
    - content.tabs.link
    - navigation.indexes
    - content.tooltips
    - navigation.path
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - navigation.tabs
  icon:
    repo: fontawesome/brands/github-alt
  logo: img/icon-white.svg
  favicon: img/favicon.png
  language: en
copyright: Copyright &copy; 2024 - Present The author of RunnelJS
nav:
  - Runnel: index.md
  - Getting Started: getting-started.md
  - Guides: guides.md
  - Libraries:
      - libraries.md
      - libraries/plugins.md
      - libraries/reporter.md
      - libraries/validator.md
plugins:
  - search
  - social
  - minify:
      minify_html: true
markdown_extensions:
  - footnotes
  - codehilite
  - extra
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/runneljs/runnel
