site_name: RunnelJS
site_description: >-
  The Solution to Micro Frontend Communication
repo_name: runneljs/runnel
repo_url: https://github.com/runneljs/runnel
theme:
  name: material
  custom_dir: overrides
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  features:
    - search.suggest
    - search.highlight
    - content.tabs.link
    - navigation.indexes
    - content.tooltips
    - navigation.path
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - navigation.tabs
  icon:
    repo: fontawesome/brands/github-alt
  favicon: img/favicon.png
  language: en
copyright: Copyright &copy; 2024 - Present Wataru Oguchi
nav:
  - Runnel: index.md
  - Getting Started:
      - getting-started/installation.md
      - getting-started/example-react.md
  - Guides: guides.md
  - Libraries:
    - libraries.md
    - libraries/runnel-validator.md
    - libraries/runnel-metric-plugin.md
    - libraries/make-your-own.md
plugins:
  - search
  - social
  - minify:
      minify_html: true
markdown_extensions:
  - footnotes
  - codehilite
  - extra
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.superfences
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/runneljs/runnel
extra_css:
  - css/extra.css